### ISSUE TITLE
JenkinsApi::Exceptions::Forbidden: Access denied. Please ensure that Jenkins is set up to allow access to this operation.

### ISSUE THREAD

**Issue by xbeta** [arangamani/jenkins_api_client#103]
Hello all,

My account which has the admin access on Jenkins and I copied my Public Key over to`https://jenkins.internal.corp.abc.com/user/xbeta/configure`

And I have this little script which basically takes a job, and update the branch information. I tried to run it but always end up with the error saying that I need to setup to allow access for this operation. But I'm not sure what access do I need to provide. Is it on Jenkins system level? or the per job level?

Thanks.

``` ruby
#!/usr/bin/env ruby
require 'jenkins_api_client'

@client = JenkinsApi::Client.new(
        :server_url => "https://jenkins.internal.corp.abc.com",
        :ssl => true,
        :identity_file => "~/.ssh/id_rsa"
)
puts @client.job.list("^releng_test$")


params = {
  :name => "releng_test",
  :scm_branch => "release-1.0.3"
}
@client.job.update_freestyle(params)
```

```
/home/jenkins/.rvm/gems/ruby-1.9.3-p385@releng_trigger_test/gems/jenkins_api_client-0.14.1/lib/jenkins_api_client/client.rb:632:in `handle_exception': Access denied. Please ensure that Jenkins is set up to allow access to this operation.  (JenkinsApi::Exceptions::Forbidden)
    from /home/jenkins/.rvm/gems/ruby-1.9.3-p385@releng_trigger_test/gems/jenkins_api_client-0.14.1/lib/jenkins_api_client/client.rb:408:in `post_config'
    from /home/jenkins/.rvm/gems/ruby-1.9.3-p385@releng_trigger_test/gems/jenkins_api_client-0.14.1/lib/jenkins_api_client/job.rb:777:in `post_config'
    from /home/jenkins/.rvm/gems/ruby-1.9.3-p385@releng_trigger_test/gems/jenkins_api_client-0.14.1/lib/jenkins_api_client/job.rb:92:in `update'
    from /home/jenkins/.rvm/gems/ruby-1.9.3-p385@releng_trigger_test/gems/jenkins_api_client-0.14.1/lib/jenkins_api_client/job.rb:210:in `update_freestyle'
    from ./test.rb:16:in `<main>'
I, [2013-09-18T01:12:35.086732 #19373]  INFO -- : Obtaining jobs matching filter '^releng_test$'
I, [2013-09-18T01:12:35.086867 #19373]  INFO -- : GET /api/json
releng_test
I, [2013-09-18T01:12:35.194464 #19373]  INFO -- : Updating job 'releng_test'
I, [2013-09-18T01:12:35.194557 #19373]  INFO -- : Posting the config.xml of 'releng_test'
I, [2013-09-18T01:12:35.194642 #19373]  INFO -- : GET /api/json
I, [2013-09-18T01:12:35.284235 #19373]  INFO -- : POST /job/releng_test/config.xml
E, [2013-09-18T01:12:35.337534 #19373] ERROR -- : JenkinsApi::Exceptions::Forbidden: Access denied. Please ensure that Jenkins is set up to allow access to this operation. 
I, [2013-09-18T01:12:35.337734 #19373]  INFO -- : GET /api/json
```

**Comment by vinpalace** [comment]
Thank you, I just had to send `:username => <username>` and `:password => <token here>`. and it worked
