### ISSUE TITLE
JenkinsApi throws ApiException when trying to retrieve config.xml of a node 

### ISSUE THREAD

**Issue by xzs424** [arangamani/jenkins_api_client#212]
**Source Code:**

`#jenkins version: 2.7.2 containerized in docker
#JenkinsApi version:  v1.4.2
#OS: CentOS 7
#Ruby version: 2.0.0

require 'jenkins_api_client'

@client = JenkinsApi::Client.new(:server_ip => 'http://mysamplejenkinsserver', :server_port => '8080',
         :username => 'root', :password => 'password')

@node = @client.node
@node_names = @node.list

for node_name in @node_names
	puts @node.get_config(node_name)
end
`

**Error Info:**

`I, [2016-08-24T16:18:27.361008 #838]  INFO -- : Obtaining nodes from jenkins matching filter ''
I, [2016-08-24T16:18:27.489422 #838]  INFO -- : Obtaining the config.xml of node 'master'
E, [2016-08-24T16:18:27.605683 #838] ERROR -- : JenkinsApi::Exceptions::ApiException:
/usr/local/share/gems/gems/jenkins_api_client-1.4.3/lib/jenkins_api_client/client.rb:779:in `handle_exception': JenkinsApi::Exceptions::ApiException (JenkinsApi::Exceptions::ApiException)
        from /usr/local/share/gems/gems/jenkins_api_client-1.4.3/lib/jenkins_api_client/client.rb:438:in `get_config'
        from /usr/local/share/gems/gems/jenkins_api_client-1.4.3/lib/jenkins_api_client/node.rb:297:in `get_config'
        from jenkins-configs.rb:13:in `block in <main>'
        from jenkins-configs.rb:12:in `each'
        from jenkins-configs.rb:12:in `<main>'`

**Comment by chinolatte** [comment]
Seems to always be the case when trying to get the config.xml of the master node, which is always the first node returned by `@node.list`
