### ISSUE TITLE
execution expired error when running script

### ISSUE THREAD

**Issue by StanleyShen** [arangamani/jenkins_api_client#219]
```
require 'jenkins_api_client'

@client = JenkinsApi::Client.new(:server_ip => 'xx.xxx.xx.xx',
         :username => 'xxxxxxxxx', :password => 'xxxxxxx')
# The following call will return all jobs matching 'Testjob'
puts @client.job.list("^Testjob")
```

And it keeps failing at error
```
/home/ubuntu/.rvm/gems/ruby-2.2.1@jenkins/gems/socksify-1.7.0/lib/socksify.rb:178:in `initialize': execution expired (Net::OpenTimeout)
	from /home/ubuntu/.rvm/gems/ruby-2.2.1@jenkins/gems/socksify-1.7.0/lib/socksify.rb:178:in `initialize'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1@jenkins/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/client.rb:319:in `make_http_request'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1@jenkins/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/client.rb:373:in `api_get_request'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1@jenkins/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/job.rb:656:in `list'
	from a.rb:10:in `<main>'
```
What should I do to make it work?

**Comment by alpinweis** [comment]
try increasing the timeout by passing the `:timeout`option to the initialization code.
e.g. `Client.new(..., timeout: 600)` will set the timeout to 600 seconds

**Comment by StanleyShen** [comment]
I tried that, it doesn't work for me. 
I even tried to set it to 6000, but no lucky.  :-(

**Comment by tonymadbrain** [comment]
same here

**Comment by DeepakRajJaganathan** [comment]
Any update on this? Am also facing the same issue.
