### ISSUE TITLE
Error while creating job 

### ISSUE THREAD

**Issue by spavez** [arangamani/jenkins_api_client#228]
I tried to create a job using a XML config from another one:

> I, [2017-03-13T14:07:13.908746 #61663]  INFO -- : Creating job 'ruby-api'
I, [2017-03-13T14:07:14.039295 #61663]  INFO -- : Crumbs turned on.  Fetching from the server.
E, [2017-03-13T14:07:14.486790 #61663] ERROR -- : JenkinsApi::Exceptions::InternalServerError: Internal Server Error. Perhaps the in-memory configuration Jenkins is different from the disk configuration. Please try to reload the configuration
/Users/spavez/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/client.rb:791:in 'handle_exception': Internal Server Error. Perhaps the in-memory configuration Jenkins is different from the disk configuration. Please try to reload the configuration (JenkinsApi::Exceptions::InternalServerError)
	from /Users/spavez/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/client.rb:469:in 'post_data'
	from /Users/spavez/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/client.rb:449:in 'post_config'
	from /Users/spavez/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jenkins_api_client-1.4.5/lib/jenkins_api_client/job.rb:104:in 'create

This is the code that I use:

`require 'jenkins_api_client' `
`@client = JenkinsApi::Client.new(:server_ip => 'localhost', :username => 'uname', :password => 'psswd')`
`@job = JenkinsApi::Client::Job.new(@client)`
`@job.create('ruby-api', 'config.xml')`

The config that I used is one of a job already working on jenkis. To get it I used the api with a curl command:

`curl -X GET http://user:token@localhost:8080/job/JOBNAME/config.xml -o config.xml` 

This is what jenkins.log shows:

> [Fatal Error] :1:1: Content is not allowed in prolog.
ERROR:  'Content is not allowed in prolog.'
Mar 13, 2017 5:21:03 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://buildfarm.sco.alma.cl:8080/createItem
java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:347)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to delete '/var/lib/jenkins/jobs/ruby-api'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at hudson.Util.deleteRecursive(Util.java:346)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:304)
	at hudson.model.ItemGroupMixIn.createTopLevelItem(ItemGroupMixIn.java:189)
	at jenkins.model.Jenkins.doCreateItem(Jenkins.java:3786)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	... 62 more
Caused by: java.nio.file.FileSystemException: /var/lib/jenkins/jobs/ruby-api/.nfs000000000c48032200000020: Device or resource busy
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1118)
	at hudson.Util.tryOnceDeleteFile(Util.java:287)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:364)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.deleteRecursive(Util.java:341)
	... 67 more

**Comment by spavez** [comment]
I have solved my problem.
The issue was that I was passing the name of the file directly. Instead I tried >File.open('mylocalconfig.xml', 'r').read
and that worked inmediatly.

Sorry for the noise, I will close this issue.
