### ISSUE TITLE
Unable to connect to the jenkins 

### ISSUE THREAD

**Issue by sumathjairaj** [arangamani/jenkins_api_client#231]
I am passing giving valid credentials still I am getting
JenkinsApi::Exceptions::Unauthorized: Invalid credentials are provided.

I, [2017-04-19T16:02:10.835361 #30632]  INFO -- : Building job 'test_job'
F, [2017-04-19T16:02:12.409195 #30632] FATAL -- : JenkinsApi::Exceptions::Unauthorized: Invalid credentials are provided.
/Users/sj050948/.rvm/gems/ruby-2.3.3/gems/jenkins_api_client-1.5.3/lib/jenkins_api_client/client.rb:782:in `handle_exception': Invalid credentials are provided. (JenkinsApi::Exceptions::Unauthorized)
	from /Users/sj050948/.rvm/gems/ruby-2.3.3/gems/jenkins_api_client-1.5.3/lib/jenkins_api_client/client.rb:377:in `api_get_request'
	from /Users/sj050948/.rvm/gems/ruby-2.3.3/gems/jenkins_api_client-1.5.3/lib/jenkins_api_client/client.rb:513:in `use_crumbs?'
	from /Users/sj050948/.rvm/gems/ruby-2.3.3/gems/jenkins_api_client-1.5.3/lib/jenkins_api_client/client.rb:682:in `refresh_crumbs'
	from /Users/sj050948/.rvm/gems/ruby-2.3.3/gems/jenkins_api_client-1.5.3/lib/jenkins_api_client/client.rb:393:in `api_post_request'
	from /Users/sj050948/.rvm/gems/ruby-2.3.3/gems/jenkins_api_client-1.5.3/lib/jenkins_api_client/job.rb:854:in `build'

**Comment by katelovescode** [comment]
Can you provide me with a little more information about your environment and how you're accessing Jenkins (through IRB or via the gem installation in your app, etc)?  If I don't hear back in a month I'll close this as stale.
