### ISSUE TITLE
get job list failed due to   `read_nonblock' error

### ISSUE THREAD

**Issue by LiYa-Xu** [arangamani/jenkins_api_client#263]
below are my code, I just want to list all jobs ,and I use sample code from README doc.

` 
  @client = JenkinsApi::Client.new(client_opts)
  puts "logged-in to the Jenkins API, use the '@client' variable to use the client"
  @client = JenkinsApi::Client.new(:server_ip => '127.0.0.1',
                                   :username => '*****', :password => '*****')
  puts @client.job.list("^test_xuliya")`

the error message 

`/Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/xuliya/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/xuliya/code/Jenkins/jenkins_api_client-master/lib/jenkins_api_client/client.rb:372:in `make_http_request'
	from /Users/xuliya/code/Jenkins/jenkins_api_client-master/lib/jenkins_api_client/client.rb:426:in `api_get_request'
	from /Users/xuliya/code/Jenkins/jenkins_api_client-master/lib/jenkins_api_client/job.rb:656:in `list'
	from /Users/xuliya/code/Jenkins/jenkins_api_client-master/scripts/login_with_irb.rb:60:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1`

**Comment by LiYa-Xu** [comment]
fixed this issue.
