### ISSUE TITLE
JenkinsApi::Exceptions::ForbiddenWithCrumb: Access denied. Please ensure that Jenkins is set up to allow access to this operation. A crumb was used in attempt to access operation. 

### ISSUE THREAD

**Issue by thebravoman** [arangamani/jenkins_api_client#300]
I have migrated to jenkins 2.249 and still started happening. 

```
E, [2020-10-14T17:46:29.384574 #4] ERROR -- : JenkinsApi::Exceptions::ForbiddenWithCrumb: Access denied. Please ensure that Jenkins is set up to allow access to this operation. A crumb was used in attempt to access operation. Access denied. Please ensure that Jenkins is set up to allow access to this operation. 
Traceback (most recent call last):
       16: from bin/rails:9:in `require'
       15: from railties (6.0.3.3) lib/rails/commands.rb:18:in `<top (required)>'
       14: from railties (6.0.3.3) lib/rails/command.rb:46:in `invoke'
       13: from railties (6.0.3.3) lib/rails/command/base.rb:69:in `perform'
       12: from thor (1.0.1) lib/thor.rb:392:in `dispatch'
       11: from thor (1.0.1) lib/thor/invocation.rb:127:in `invoke_command'
       10: from thor (1.0.1) lib/thor/command.rb:27:in `run'
        9: from railties (6.0.3.3) lib/rails/commands/console/console_command.rb:102:in `perform'
        8: from railties (6.0.3.3) lib/rails/commands/console/console_command.rb:19:in `start'
        7: from railties (6.0.3.3) lib/rails/commands/console/console_command.rb:70:in `start'
        6: from (irb):3
        5: from (irb):3:in `rescue in irb_binding'
        4: from lib/jenkins_client_factory.rb:11:in `force_job_workoff'
        3: from jenkins_api_client (26f0de9cab9b) lib/jenkins_api_client/job.rb:858:in `build'
        2: from jenkins_api_client (26f0de9cab9b) lib/jenkins_api_client/client.rb:422:in `api_post_request'
        1: from jenkins_api_client (26f0de9cab9b) lib/jenkins_api_client/client.rb:450:in `rescue in api_post_request'
JenkinsApi::Exceptions::ForbiddenWithCrumb (Access denied. Please ensure that Jenkins is set up to allow access to this operation. A crumb was used in attempt to access operation. Access denied. Please ensure that Jenkins is set up to allow access to this operation. )
```

The client is created with 
```
  def self.new_client
    ENV["JENKINS_USERNAME"] || raise("no JENKINS_USERNAME provided")
    ENV["JENKINS_PASSWORD"] || raise("no JENKINS_PASSWORD provided")

    crt = (ENV["JENKINS_CRT"] || File.read("#{Rails.root}/keys/platform@jenkins.crt.pem"))
    crt || raise("no JENKINS_CRT provided")
    key = (ENV["JENKINS_KEY"] || File.read("#{Rails.root}/keys/platform@jenkins.key.pem"))
    key || raise("no JENKINS_KEY provided")

    # This crt and key files could be generated with
    # openssl pkcs12 -in path.p12 -out newfile.crt.pem -clcerts -nokeys
    # openssl pkcs12 -in path.p12 -out newfile.key.pem -nocerts -nodes
    # This of course is only if you have p12 file.
    JenkinsApi::Client.new(:server_url=>CAST_CONFIG["jenkins"]["server_url"],
                           crt: crt,
                           key: key,
                           ssl: true,
                           :username=>ENV["JENKINS_USERNAME"],
                           :password=>ENV["JENKINS_PASSWORD"])
  end
```

and the call is
 
```
new_client.job.build(build_name, {"param1"=>value1})
```

**Comment by thebravoman** [comment]
I managed to fix this by adding

```
    end

      http.open_timeout = @http_open_timeout
      http.read_timeout = @http_read_timeout

      response = http.request(request)
+      @cookies = response["set-cookie"]
      case response
        when Net::HTTPRedirection then
          # If we got a redirect request, follow it (if flag set), but don't
          # go any deeper (only one redirect supported - don't want to follow
          # our tail)
          if follow_redirect
            redir_uri = URI.parse(response['location'])
            response = make_http_request(
              Net::HTTP::Get.new(redir_uri.path, false)
            )
          end
      end

```

I will prepare a pull request for this.

**Comment by jesseadams** [comment]
This didn't fix my issue, but https://github.com/arangamani/jenkins_api_client/pull/292 did.

**Comment by thebravoman** [comment]
@NathanZook by "this is a wholly inadequate" do you mean https://github.com/arangamani/jenkins_api_client/pull/292 or you mean

```
      response = http.request(request)
+      @cookies = response["set-cookie"]
      case response
        when Net::HTTPRedirection then
```

If it is the second one, then yes, this is a workaround for my case that gives more information about the issue, but it is not a solution to the issue.
